# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.2

    environment: GO111MODULE=on

    working_directory: /go/src/github.com/nikogura/dbt
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: gpg-agent --daemon
      - run: go test -v ./...
      - run: go get github.com/mattn/goveralls
      - run: go test -v -cover -race -coverprofile=/tmp/coverage.out ./pkg/dbt
      - run: goveralls -coverprofile=/tmp/coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN

