---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dbt
  namespace: dbt
data:
  reposerver.json: |
    {
      "address": "0.0.0.0",
      "port": 9999,
      "serverRoot": "/var/dbt",
      "authType": "basic-htpasswd",
      "authGets": false,
      "authOpts": {
        "idpFile": "/etc/dbt/htpasswd"
      }
    }

  htpasswd: |
    nik:$apr1$ytmDEY.X$LJt5T3fWtswK3KF5iINxT1
